### ISSUE TITLE
merchant and nomads not finding path to village in latest release and pathing issues with standard villagers

### ISSUE THREAD

**Issue by DS9Fireblade** [TangoTek/TekTopia-Community#64]
have downloaded the latest release of tektopia and keep having a message appear in my chat window saying my village is no accessible, i have no bounding walls or obstructions surrounding my village. Also have noticed villages getting stuck in water ways used in naturally generated village farms, wont path find out even when being attacked by hostiles.

**Comment by luvzdeidara** [comment]
**Describe the bug**
I rennovated a naturally generated village using the latest release of TekTopia. 
When I finally placed down the Town Hall token, I receive the following message when day comes:
"Merchant failed to find a way to the village."
"Nomand failed to find a way to the village."

I've punched out all the Town Hall tokens in the surrounding villages in a 400 Block radius.
I've built paths over nearby rivers.

**To Reproduce**
Sleep through the night.
When merchant and nomads would normally show up, message pops up in chat.

**Expected behavior**
Would expect them to be able to get to my new village.

**Screenshots**


** Server/Location **
Singleplayer (survival/Creative)
![2019-05-26_20 57 26](https://user-images.githubusercontent.com/51054914/58389660-6ab04800-7ffa-11e9-838c-823e80724ebe.png)

**Comment by asgasgasg** [comment]
This is happening to me as well. Wide open field surrounding, although there's water in the distance, so I'm wondering if the nomads/merchants are attempting to spawn over water and it won't let them.

**Comment by asgasgasg** [comment]
I just tried moving the entrance to the town hall to a different door on the same building, no luck

**Comment by iSyriux** [comment]
The same thing happened to me, the support for tektopia is absolute **SHIT**. Literally, the nomads and the merchant will go in front of the town hall doors and just stand there, eventually they despawn and give the error message, it's fucking frustrating. I go to the discord server and ask, and is banned almost immediately, keep in mind, i had two accounts, the first time, I got banned, the second time, same thing. This isn't an accident or anything tektopia is fucking shit.

**Comment by DS9Fireblade** [comment]
> The same thing happened to me, the support for tektopia is absolute **SHIT**. Literally, the nomads and the merchant will go in front of the town hall doors and just stand there, eventually they despawn and give the error message, it's fucking frustrating. I go to the discord server and ask, and is banned almost immediately, keep in mind, i had two accounts, the first time, I got banned, the second time, same thing. This isn't an accident or anything tektopia is fucking shit.

Have you checked your in the latest version this was fixed very quickly I found and as for the lack of support there is one guy who built this, and if this was how you acted in the discord it will explain why you were banned

**Comment by iSyriux** [comment]
![image](https://user-images.githubusercontent.com/38577487/76876835-e230bb80-6848-11ea-84b1-51c55e977082.png)

**Comment by iSyriux** [comment]
https://github.com/TangoTek/TekTopia-Community/issues/395

**Comment by iSyriux** [comment]
ds9fireblade IMAGINE BEING FUCKING BRAINDEAD FUCKING ASSHOLE YOUR BRAIN IS SMALLER THAN A FUCKING NUT YOU IDIOT RETARD

**Comment by iSyriux** [comment]
MY VERSION IS THE LATEST, LITERALLY TANGO TEK UPDATED IT TWICE, 1.0.0 AND 1.1.0. I HAVE 1.1.0, YET BUG STILL HERE! GREAT! FUCK TANGO!

**Comment by iSyriux** [comment]
RDSTER YOU FUCKING MORON ARE YOU FUCKING KIDDING ME YOU FUCKING ASSHGOLE FUCKING PEABRAIN THE NOMADS WILL FIND A WAY TO THE VILLAGE AND ASSIGN THEMSELVES BEDS YES YOU NEED TO ASSIGN THEM PROFESSIONS BUT THEY WILL ASSIGN THEMSELVES BEDS AND WEAR WILL A GREEN OUTFIT AND THEY WONT DESPAWN AND GIVE THAT FUCKING STUPIDASS ERROR MESSAGE

**Comment by DS9Fireblade** [comment]
> ds9fireblade IMAGINE BEING FUCKING BRAINDEAD FUCKING ASSHOLE YOUR BRAIN IS SMALLER THAN A FUCKING NUT YOU IDIOT RETARD

Yet I'm not the one who resorts to this language and as I previously stated there is only one person who works on this mod and that is tango himself, he is currently working on hermitcraft and has decided to  Prioritise hermitcraft. He has said that he will try to run an update later in the year, but obviously you can't seem to understand that. Also maybe check that there are paths for the nomads to follow, if that fails then maybe grow up and ask others if they are still having this issue not go f'ing and blinding at others because it hasn't gone your way

**Comment by iSyriux** [comment]
I CANT FUCKING POST ON HIS THREAD BECAUSE HE FUCKING CLOSED IT OFF AND THE LAST MESSAGE WAS TO FUCKING REPORT ME THAT FUCKING MORON FUCK HIM AND HIS FAMILY FUCK HIM I WISH HE'D FUCKING DIE HE FUCKING MORON FUCKING SHITBAD FUCK HIM BURN HIS FUCKING ASSHOLE FUCKING NIGGER ASS BITCH CUNT FAGGOT MORON BITCHASS BASTARD FUCKING MORON FUCKING NIGGER NIGGER NIGGER ASSHOLE CUNTASS FUCKING TERRORIST FUCKING ARABIAN FUCKING TERRORIST

**Comment by iSyriux** [comment]
HE FUCKING REPORTED ME

**Comment by iSyriux** [comment]
TELL ME THATS NOT FUCKING UNFAIR

**Comment by DS9Fireblade** [comment]
Maybe if you were grown up you may not have people report you. There is no need for this language

**Comment by iSyriux** [comment]
imagine minecraft was like this

**Comment by iSyriux** [comment]
minecraft: new update you cant mine blocks its a bug ill fix it next year

**Comment by iSyriux** [comment]
minecraft next year: WHERE MY PEOPLE GO WTF

**Comment by iSyriux** [comment]
I LOST BILLION DOLLARS WTF

**Comment by iSyriux** [comment]
microsoft: bans minecraft from the usa

**Comment by iSyriux** [comment]
macosoft: mic

**Comment by iSyriux** [comment]
MICR

**Comment by DS9Fireblade** [comment]
> minecraft: new update you cant mine blocks its a bug ill fix it next year

As I have said it is one person working on this, whereas mojang has 100's and yes they have hundreds as they are supported now by Microsoft. His job is full time YouTube so if he stops that and works on this mod he looses his livelihood so yes it will be later in the year when he gets a chance to
